### ISSUE TITLE
Cannot connect to Docker daemon

### ISSUE THREAD

**Issue by joppa27** [cloudera/clusterdock#1]
When I try to do the default 2 node cluster start, the startup script fails because it is unable to connect to the docker daemon.  There may be some network issues on my side, but I'll try to provide as much info as I can. I created a docker-machine named hadoop, and ran a 
`eval $(docker-machine env hadoop)` to ensure my current terminal is configured to talk to the daemon.

1. Cloned this repo
2. ran `source ./clusterdock.sh`
3. when I run `clusterdock_run ./bin/start_cluster cdh`  I get an error that it can't talk to the daemon

```Warning: failed to get default registry endpoint from daemon (Cannot connect to the Docker daemon. Is the docker daemon running on this host?). Using system default: https://index.docker.io/v1/
Cannot connect to the Docker daemon. Is the docker daemon running on this host?
docker: Cannot connect to the Docker daemon. Is the docker daemon running on this host? ```


I'm currently running docker-toolbox with docker version 1.11.2, any suggestions for what I may be doing wrong?

Thanks,

**Comment by dimaspivak** [comment]
Hey Joppa,

The script assumes it's run from a host that has Docker installed and has no specific docker-machine support (mostly because of the resource requirements we spell out in terms of RAM).

**Comment by joppa27** [comment]
Ah, oic. That makes sense, I'll try again with a standalone install.

Thanks for the quick response!
