### ISSUE TITLE
clusterdock.sh helper script issue when creating container

### ISSUE THREAD

**Issue by einarvelez** [cloudera/clusterdock#21]
When trying to create the container:
docker create command (line 80) fails because cannot create mount volume as file already exists.
We have removed all volumes and tried again but keeps returning that error.

Could you please help us?

Thanks and regards,

**Comment by einarvelez** [comment]
Hi Dima,

This is the info, we think it could be because our server is not reaching docker.io, we have contacted the security team to check if the connection is locked because of the proxy:

CentOS Linux release 7.2.1511 (Core)
NAME="CentOS Linux"
VERSION="7 (Core)"
ID="centos"
ID_LIKE="rhel fedora"
VERSION_ID="7"
PRETTY_NAME="CentOS Linux 7 (Core)"
ANSI_COLOR="0;31"
CPE_NAME="cpe:/o:centos:centos:7"
HOME_URL="https://www.centos.org/"
BUG_REPORT_URL="https://bugs.centos.org/"

CENTOS_MANTISBT_PROJECT="CentOS-7"
CENTOS_MANTISBT_PROJECT_VERSION="7"
REDHAT_SUPPORT_PRODUCT="centos"
REDHAT_SUPPORT_PRODUCT_VERSION="7"


uname -r
3.10.0-327.10.1.el7.x86_64



sudo docker info
Containers: 6
Running: 0
Paused: 0
Stopped: 6
Images: 6
Server Version: 1.12.5
Storage Driver: devicemapper
Pool Name: docker-202:1-1216348295-pool
Pool Blocksize: 65.54 kB
Base Device Size: 10.74 GB
Backing Filesystem: xfs
Data file: /dev/loop0
Metadata file: /dev/loop1
Data Space Used: 10.15 GB
Data Space Total: 107.4 GB
Data Space Available: 97.23 GB
Metadata Space Used: 7.094 MB
Metadata Space Total: 2.147 GB
Metadata Space Available: 2.14 GB
Thin Pool Minimum Free Space: 10.74 GB
Udev Sync Supported: true
Deferred Removal Enabled: false
Deferred Deletion Enabled: false
Deferred Deleted Device Count: 0
Data loop file: /var/lib/docker/devicemapper/devicemapper/data
WARNING: Usage of loopback devices is strongly discouraged for production use. Use `--storage-opt dm.thinpooldev` to specify a custom block storage device.
Metadata loop file: /var/lib/docker/devicemapper/devicemapper/metadata
Library Version: 1.02.135-RHEL7 (2016-11-16)
Logging Driver: journald
Cgroup Driver: systemd
Plugins:
Volume: local
Network: null overlay host bridge
Swarm: inactive
Runtimes: docker-runc runc
Default Runtime: docker-runc
Security Options: seccomp selinux
Kernel Version: 3.10.0-327.10.1.el7.x86_64
Operating System: CentOS Linux 7 (Core)
OSType: linux
Architecture: x86_64
Number of Docker Hooks: 2
CPUs: 8
Total Memory: 57.81 GiB
Name: ip-10-64-35-13.cm.es
ID: O77A:5TI7:MCAR:6YYH:S4S5:5IKD:KIGV:IXKR:5L5U:G6HB:TSBE:RSJ4
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): false

**Comment by dimaspivak** [comment]
I'd actually blame devicemapper. CentOS is notoriously buggy when it comes
to Docker so I'd highly recommend using Ubuntu instead.
-- 
-Dima

**Comment by einarvelez** [comment]
Hi Dima,

However, despite we resolve the docker.io connectivity issue, we think we will have an issue as we did some workarounds to retrieve the image and we were having the volumen mount issue. Could it be because of the devicemapper?

Thanks

**Comment by dimaspivak** [comment]
Yes. Dump CentOS and use Ubuntu for Docker hosts and you'll probably never
have this issue.
-- 
-Dima

**Comment by einarvelez** [comment]
Thanks Dima we will try
