### ISSUE TITLE
how can I get a single node running?

### ISSUE THREAD

**Issue by cirpo** [cloudera/clusterdock#9]
I can't find a docker image with Cloudera quickstart 5.8 (was it removed?) so I tried to run the clusterdock but it fails:

```
clusterdock_run ./bin/start_cluster cdh
Password:
INFO:clusterdock.cluster:Successfully started node-1.cluster (IP address: 192.168.123.2).
INFO:clusterdock.cluster:Successfully started node-2.cluster (IP address: 192.168.123.3).
INFO:clusterdock.cluster:Started cluster in 7.18 seconds.
INFO:clusterdock.topologies.cdh.actions:Changing server_host to node-1.cluster in /etc/cloudera-scm-agent/config.ini...
INFO:clusterdock.topologies.cdh.actions:Restarting CM agents...
cloudera-scm-agent is already stopped
cloudera-scm-agent is already stopped
Starting cloudera-scm-agent: [  OK  ]
Starting cloudera-scm-agent: [  OK  ]
INFO:clusterdock.topologies.cdh.actions:Waiting for Cloudera Manager server to come online...
INFO:clusterdock.topologies.cdh.actions:Detected Cloudera Manager server after 80.14 seconds.
INFO:clusterdock.topologies.cdh.actions:CM server is now accessible at http://moby:32769
INFO:clusterdock.topologies.cdh.cm:Detected CM API v13.
INFO:clusterdock.topologies.cdh.cm_utils:Updating database configurations...
INFO:clusterdock.topologies.cdh.cm:Updating NameNode references in Hive metastore...
INFO:clusterdock.topologies.cdh.actions:Once its service starts, Hue server will be accessible at http://moby:32768
INFO:clusterdock.topologies.cdh.actions:Deploying client configuration...
INFO:clusterdock.topologies.cdh.actions:Starting cluster...
Traceback (most recent call last):
 File "./bin/start_cluster", line 70, in <module>
   main()
 File "./bin/start_cluster", line 63, in main
   actions.start(args)
 File "/root/clusterdock/clusterdock/topologies/cdh/actions.py", line 154, in start
   raise Exception('Failed to start cluster.')
Exception: Failed to start cluster.
```

My main goal is to run a single node with the 5.8 version, but if I try to pull and run:

```
docker run --privileged=true -t -i cloudera/clusterdock:cdh580_cm581_primary-node
```

I get: 

```
docker: Error response from daemon: cannot mount volume over existing file, file exists /var/lib/docker/aufs/mnt/56e28b0df13816188a2d4cf7bff617cad2e77f3d764abf6ee608f67c0bd6724a/etc/localtime
```

how can I get a docker image for the 5.8 quickstart version? 

thanks

**Comment by dimaspivak** [comment]
Hi cirpo,

What kind of machine are you trying to run this on (e.g. OS, CPUs, RAM)?

**Comment by cirpo** [comment]
@dimaspivak Macbook Pro 2.7 GHz Intel Core i5 16GB of Ram.
In the team we are interested on running the quickstart image, but with the 5.8 version, not the 5.7

**Comment by cirpo** [comment]
@dimaspivak I understand I'm getting this error probably becuase I don't have enough resource, but my main goal is to have a single instance with CDM 5.8 and unfortunately the cloudera/quickstart image, which is running super fine on my machine, has the previous 5.7 version.

**Comment by dimaspivak** [comment]
Yeah, the QuickStart Docker image disabled a lot of the things that used resources, which is likely why it ran for you before. Wanna try using clusterdock again, but this time, add `--dont-start-cluster` to the end. Then you can log into CM and only start the services you need/that your machine can handle.

**Comment by cirpo** [comment]
@dimaspivak thanks, I will try

**Comment by iasinDev** [comment]
Hi, I had the same problem some days ago, I searched across diferent same issues .... Finally I concluded it's due to ram resources error. I saw that after this error I was able to start cloudera manager through command line but after some seconds it crushed, I tried with at least 20 GB for the cluster, and it worked. To sum sup, the startup script wait to cloudera is up to continue but due to inssuficient resources, cloudera manager is not able to start, so it fails.

**Comment by SuriMS** [comment]
Hi Dima,

I have got everything set up in a server, and I am able to  run clusterdock_run ./bin/start_cluster cdh and the containers are up and running. But when I try to perform clusterdock_ssh node-1.cluster-- it says sudo: clusterdock_ssh: command not found. I tried to delete the image completely and re-do all the process- still I am not able to get the terminal for any node. I can access the hue though. Can you please help?

**Comment by dimaspivak** [comment]
Please open a new issue, @SuriMS.
